Initial Dev Onboarding + Resources
pathwaystoeducation/get-started pull request #1
Opened 2020-10-27 17:05 UTC by shubsengupta

This will serve as a living doc for dev onboarding resources + best practices for contributors to Pathways To Education repositories.

2020-10-28 18:07 UTC, orangecubedigital requested changes
Would suggest linking ProductBoard

2020-10-28 18:10 UTC, shubsengupta commented
> Would suggest linking ProductBoard

Good call, on it. Thanks!

2020-10-29 19:50 UTC, jasonshim commented on README.md
> +We create + share technologies optimized for impact in the areas of youth well-being and education.
```suggestion
We create + share technology optimized for impact in the areas of youth well-being and education. 
```

2020-10-29 19:51 UTC, jasonshim commented on README.md
> +  (e.g. "**Add UI for Login Page**", or "**Remove Extra Character to Fix #21**", referencing Github Issues if needed)
```suggestion
  (e.g. "**Add UI for Student Login Page**", or "**Remove Extra Character to Fix #21**", referencing Github Issues if needed) 
```
Including addition of word student to add context b/c this is particular to Pathways. :)

2020-10-29 19:52 UTC, jasonshim commented on README.md
> +- Create pull-requests and always ensure PR (Pull Request) is reviewed and approved before merging. This should at the very minimum be you reviewing your own code as a third party, but ideally involv
```suggestion
- Create pull-requests and always ensure PR (Pull Request) is reviewed and approved before merging. At the very minimum, this should be a thorough review of your own code, but ideally involves a third-party review by at least one other member of the team.
```

2020-10-29 19:53 UTC, jasonshim commented on README.md
> +- Feedback is sent in email, slack, or other medium and should be logged as an Insight in [ProductBoard](https://pathwayscanada.productboard.com/feature-board/1972714-feature-organization) *(Requires
```suggestion
- Feedback sent in email, Slack, or other channels and should be logged as an Insight in [ProductBoard](https://pathwayscanada.productboard.com/feature-board/1972714-feature-organization) *(Requires Login)*
```

2020-10-29 19:57 UTC, jasonshim commented on README.md
> +- Code should be worked on in a separate branch based on the latest master, unless absolutely required otherwise
```suggestion
- Code should be worked on in a separate branch based on the latest main, unless absolutely required otherwise
```

2020-10-29 19:57 UTC, jasonshim commented on README.md
> +- Code should be worked on in a separate branch based on the latest master, unless absolutely required otherwise
To reflect Github change https://github.com/github/renaming

2020-10-29 19:59 UTC, shubsengupta commented on README.md
> +- Code should be worked on in a separate branch based on the latest master, unless absolutely required otherwise
Good catch, thank you!

2020-10-29 19:59 UTC, jasonshim commented on README.md
> +- Address any feedback, and merge PRs only when approved by at least one reviewer by using "Squash and Merge."
Squash and Merge - may need more context? Is there a link or info that can be provided? Or is it assumed that anyone reading would inherently know what it references?

2020-10-29 20:01 UTC, shubsengupta commented on README.md
> +- Address any feedback, and merge PRs only when approved by at least one reviewer by using "Squash and Merge."
Good call - it's a dropdown when merging a PR, but I can link to it for now. For future, we can enable this as a default for branches so we'll just use that!

2020-10-29 20:05 UTC, jasonshim approved these changes
Looks good!

2020-10-29 20:06 UTC, merged